<?php

  function cipher_menu() {
    $items = array();
    $items['cipher'] = array(
      'title' => 'Shift Cipher',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('cipher_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );
    return $items;
  }

  function cipher_form() {
    $form['shift_value'] = array(
      '#title' => 'Shift value',
      '#type' => 'textfield',
      '#description' => t('Enter Shift Value here'),
    );

    $form['shift_direction'] = array(
      '#title' => 'Shift direction',
      '#type' => 'textfield',
      '#description' => t('Enter the direction you\'d like to shift in.'),
    );

    $form['shift_phrase'] = array(
      '#title' => 'Shift phrase',
      '#type' => 'textfield',
      '#description' => t('Enter the phrase you\'d like shifted.'),
    );

    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Shift',
    );

    return $form;
  }

  function cipher_form_submit($form, &$form_state) {
    $form_state['redirect'] = 'cipher_success_page';
  }
